### ISSUE TITLE
Yolo project not showing up in the participants directory

### ISSUE THREAD

**Issue by dineshshenoy** [filecoin-project/slingshot#100]
@momack2 @mosh @Jennifer Hi, our project Yolo's PR(https://github.com/filecoin-project/slingshot/pull/26) has been merged, however, i couldn't find it in the https://github.com/filecoin-project/slingshot/tree/master/participants list, what happened?

**Comment by yuwenhui** [comment]
So, what happened? is there any mistake?

**Comment by dineshshenoy** [comment]
https://github.com/filecoin-project/slingshot/pull/127
