### ISSUE TITLE
[For Storage Miners] Bad actor list suggested by community members

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/slingshot#119]
This is suggested by Chris, Reiers and Meatball from Filecoin slack. The purpose of this ticket is to have a place that holds a list of bad actors that are suggested by the community members, and storage miners can refer to for configuring their deal filter.

**Disclaimer: Any claim in this ticket is not/will not be verified by the official Filecoin team! Please use your own judgement for your filter configuration! 👀**

**Comment by flyworker** [comment]
Message: adding market funds failed: resolve address t3qkxap3won44eupavf6kuggy5v5j24bkql5atn2iyqmd4ifqmjtemslvcakkgm7gcvf6e2hwfxjjio6zna7uq: actor not found
...yek3afrm  0       t019437   StorageDealError         N                N            ...l5oepkfa  127 KiB    0.00000006353413911 FIL   1040946   
  Message: adding market funds failed: resolve address t3qkxap3won44eupavf6kuggy5v5j24bkql5atn2iyqmd4ifqmjtemslvcakkgm7gcvf6e2hwfxjjio6zna7uq: actor not found
...rqazy6pe  0       t03275    StorageDealError         N                N            ...l5oepkfa  127 KiB    0.000000063598042755 FIL  1041993   
  Message: adding market funds failed: resolve address t3qkxap3won44eupavf6kuggy5v5j24bkql5atn2iyqmd4ifqmjtemslvcakkgm7gcvf6e2hwfxjjio6zna7uq: actor not found
...jp6kmzie  0       t05317    StorageDealError         N                N            ...l5oepkfa  127 KiB    0.000000063610127685 FIL  1042191   
  Message: adding market funds failed: resolve address t3qkxap3won44eupavf6kuggy5v5j24bkql5atn2iyqmd4ifqmjtemslvcakkgm7gcvf6e2hwfxjjio6zna7uq: actor not found
...h3mu5ezu  0       t01238    StorageDealError         N                N            ...l5oepkfa  127 KiB    0.00000006353597016 FIL   1040976   
  Message: adding market funds failed: resolve address t3qkxap3won44eupavf6kuggy5v5j24bkql5atn2iyqmd4ifqmjtemslvcakkgm7gcvf6e2hwfxjjio6zna7uq: actor not found
...nyo34a3i  0       t01278    StorageDealError         N                N            ...x3ffi6ja  254 KiB    0.000000025410799206 FIL  1040829   
  Message: adding market funds failed: resolve address t3qkxap3won44eupavf6kuggy5v5j24bkql5atn2iyqmd4ifqmjtemslvcakkgm7gcvf6e2hwfxjjio6zna7uq: actor not found
...m2pvksna  0       t02620    StorageDealError         N                N            ...x3ffi6ja  254 KiB    0.00000002538506685 FIL   1039775   
  Message: adding market funds failed: resolve address t3qkxap3won44eupavf6kuggy5v5j24bkql5atn2iyqmd4ifqmjtemslvcakkgm7gcvf6e2hwfxjjio6zna7uq: actor not found
...ec6jpxpu  0       t016563   StorageDealError         N                N            ...x3ffi6ja  254 KiB    0.000000025427596038 FIL  1041517   
  Message: adding market funds failed: resolve address t3qkxap3won44eupavf6kuggy5v5j24bkql5atn2iyqmd4ifqmjtemslvcakkgm7gcvf6e2hwfxjjio6zna7uq: actor not found
...zfpuv3a4  0       t09833    StorageDealError         N                N            ...vchfiqby  127 KiB    0.00000006349617534 FIL   1040324   
  Message: adding market funds failed: resolve address t3qkxap3won44eupavf6kuggy5v5j24bkql5atn2iyqmd4ifqmjtemslvcakkgm7gcvf6e2hwfxjjio6zna7uq: actor not found
...7z75bbem  0       t02620    StorageDealError         N                N            ...vchfiqby  127 KiB    0.000000012692277078 FIL  1039754   
  Message: adding market funds failed: resolve address t3qkxap3won44eupavf6kuggy5v5j24bkql5atn2iyqmd4ifqmjtemslvcakkgm7gcvf6e2hwfxjjio6zna7uq: actor not found
...scjwbrnm  0       t08937    StorageDealError         N                N            ...vchfiqby  127 KiB    0.000000012707194032 FIL  1040976   
  Message: adding market funds failed: resolve address t3qkxap3won44eupavf6kuggy5v5j24bkql5atn2iyqmd4ifqmjtemslvcakkgm7gcvf6e2hwfxjjio6zna7uq: actor not found
...wh6y6bfm  0       t02620    StorageDealError         N                N            ...x3ffi6ja  254 KiB    0.00000002538409029 FIL   1039735

**Comment by Reiers** [comment]
**Address:** t1tpj5gm2i3jcbarmhvxsmpp3he4hbrngrtbf54eq
**Problem:** Stuck in StorageDealTransferring
**Size:** 1GiB

_Maybe not a bad actor. But this address have been reported by at least 4 miners with the same problem._

**Comment by cwhiggins** [comment]
This is also the only t1 address that I have seen being used. Does it matter?

**Comment by pooja** [comment]
This issue is now quite outdated, so we'll be closing it, but please reopen or create a new issue if needed
