### ISSUE TITLE
Applicant (IPFS-scholar) orphaned outside of subdirectory

### ISSUE THREAD

**Issue by orvn** [filecoin-project/slingshot#170]
An application,`IPFS-scholar.md`, was [accidentally merged into](https://github.com/filecoin-project/slingshot/commit/ec6d4b60a40fa14c7df348e1d9df0eea951a3b32) the root of the repository. Instead of being correctly nested in `/participants/`.

**Comment by dineshshenoy** [comment]
Thanks for catching.  Fixed as part of: https://github.com/filecoin-project/slingshot/pull/173
