### ISSUE TITLE
[For Clients] "Bad" miner list suggested by community members

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/slingshot#198]
The purpose of this ticket is to have a place that holds a list of bad miners(not accepting deals, node has long down time..) that are suggested by the community members, and clients
can refer to this to decide the miner they want to have the deal with.

Disclaimer: Any claim in this ticket is not/will not be verified by the official Filecoin team! Please use your own judgement when you chose your miner! 👀

**Comment by pooja** [comment]
We're building this into the judging directly in Slingshot 2.3!
