### ISSUE TITLE
[Phase 2] Interested in Slingshot Phase 2? Comment here with your contact details!

### ISSUE THREAD

**Issue by dchoi27** [filecoin-project/slingshot#348]
Hi! We are currently getting ready to finalize details about Slingshot Phase 2. These will be ready by early to mid November. 

In the meantime, if you are interested, please review [this Slack announcement](https://filecoinproject.slack.com/archives/C01AK1J7TF1/p1603738868285700) and comment below with your Filecoin Slack handle and/or Phase 1 project submission ID (if applicable)

**Comment by Q-Action** [comment]
Submission ID: 678911992

**Comment by liyunzhi-666** [comment]
project name: Starry Sky in Yunnan
Submission ID: 667718849
Slack handle: Patrick-li

**Comment by liyunzhi-666** [comment]
project name: Filecoin-Crawl 
Submission ID: 667706600
Slack handle: Patrick-li

**Comment by yuwenhui** [comment]
project name: Yolo
Submission ID: 666165170
Slack handle: Max

**Comment by koda9-inc** [comment]
Project Name: Robotic Dog Data Collecting

**Comment by yongxi-liu** [comment]
Project Name: Filbox
sumission ID: 667174272
Slack Handle: kimmy.w ；leo.r

**Comment by ffteng47** [comment]
Project Name: FortuneCode
sumission ID: 667519588
Slack Handle: jerrify

**Comment by CDYulinChen** [comment]
Project Name: Smartcity
sumission ID: 672747283
Slack Handle: klsmlzm

**Comment by CDYulinChen** [comment]
Project Name: Medical Image Cloud System
sumission ID: 670234252
Slack Handle: klsmlzm

**Comment by priom** [comment]
Project Name: ChainSafe Files
Submission ID: 673803650
Slack Handle: priom

**Comment by joeylee3548** [comment]
Slack handle : joeylee

**Comment by koda9-inc** [comment]
Project name: KodaRobotDog
Submission ID:672993312)
Slack Handle: koda9-inc

**Comment by guowenshuai** [comment]
Project Name: datamain
Submission ID: 668425487
Slack Handle: simon

**Comment by guowenshuai** [comment]
Project Name: lookiso
Submission ID: 681114360
Slack Handle: simon

**Comment by Filecoin-ypool** [comment]
Project Name: cloudEyes
Submission ID: 667094906
Slack Handle: huangdongjin

**Comment by pooja** [comment]
Slingshot 2 is now well underway! Closing this issue
