### ISSUE TITLE
A project (参加者) is incorrectly nested in the root of the repo

### ISSUE THREAD

**Issue by orvn** [filecoin-project/slingshot#357]
A project, [参加者, is not nested](https://github.com/filecoin-project/slingshot/commits/master/%E5%8F%82%E5%8A%A0%E8%80%85) in the`participants` directory.

(Just mentioning this for house keeping's sake)

**Comment by pooja** [comment]
@orvn Is it ok for us to close this issue?

**Comment by orvn** [comment]
Yes, definitely. That's all legacy content anyway.

Actually I just moved that directory to the correct place and created a PR [`pull/445`](https://github.com/filecoin-project/slingshot/pull/445).

**Comment by orvn** [comment]
Yes, definitely @pooja. That's all legacy content anyway.

Actually I just moved that directory to the correct place and created a PR [`pull/445`](https://github.com/filecoin-project/slingshot/pull/445).

**Comment by pooja** [comment]
Great!
