### ISSUE TITLE
Request to add own data set to curated list

### ISSUE THREAD

**Issue by ipfs-weraveyou** [filecoin-project/slingshot#388]
Dataset Name: We Rave You
Description: List of videos from artists and curators from the We Rave You community 
File type: MP4
Size: n/a
URL: https://weraveyou.com

Please check if this is correct - [WeRaveYou-dataset.xlsx](https://github.com/filecoin-project/slingshot/files/5651114/WeRaveYou-dataset.xlsx)

@dineshshenoy

**Comment by pooja** [comment]
We're closing this issue since it's been many months, but please reopen if desired
