### ISSUE TITLE
Add a own smartcity's dataset to curated list for Phase 2 of SR2.

### ISSUE THREAD

**Issue by xingjitansuo** [filecoin-project/slingshot#389]
Dataset Name: Smartcity Audio Dataset
Description:  List the audios from collected by fiber optic sensor in our city!
File type: WAV
Size: above 30T
URL: http://api.sr2.glm2m.com/index.php?r=smartcity-dataset/index

Please check if this is correct , thank you!

@dineshshenoy

**Comment by pooja** [comment]
We're closing this issue since it's been many months, but please reopen if desired
