### ISSUE TITLE
Add Dataset [Genome Aggregation Database][35.7 TiB]

### ISSUE THREAD

**Issue by gayeley** [filecoin-project/slingshot#404]
Dataset info : https://github.com/awslabs/open-data-registry/blob/master/datasets/broad-gnomad.yaml
Name: UK Biobank Pan-Ancestry Summary Statistics
Description: A multi-ancestry analysis of 7,221 phenotypes using a generalized mixed model association testing framework, spanning 16,119 genome-wide association studies. We provide standard meta-analysis across all populations and with a leave-one-population-out approach for each trait. The data are provided in tsv format (per phenotype) and Hail MatrixTable (all phenotypes and variants). Metadata is provided in phenotype and variant manifests.

**Comment by pooja** [comment]
We're closing this issue since it's been many months, but please reopen if desired
