### ISSUE TITLE
Add Dataset [Open Source Software Mirror Station of Beijing Foreign Studies University][80.2 TiB]

### ISSUE THREAD

**Issue by Haoahao233** [filecoin-project/slingshot#410]
Dataset info : https://mirrors.bfsu.edu.cn/#
Name: Open Source Software Mirror Station of Beijing Foreign Studies University
Description: The open source software image station of Beijing Foreign Studies University is dedicated to providing high-quality open source software image and Linux image source services for domestic and campus users, so as to help users obtain open source software more easily.

**Comment by pooja** [comment]
We're closing this issue since it's been many months, but please reopen if desired
