### ISSUE TITLE
DataStoneCloud-Intelligent video solution  Surveillance video DataSets

### ISSUE THREAD

**Issue by jackeyprince** [filecoin-project/slingshot#414]
DataStoneCloud-Intelligent video solution  Base On Filecoin/IPFS.  The intelligent video solution is specially designed to meet the requirements for storage of the data from PB to EB-level video surveillance. The system can have its performance increase linearly with the increase of its capacity, able to maintain a smooth cost for capacity expansion, lower the cost for operation and maintenance management in the context of the continuous growth of the data volume, support the integration of the existing infrastructure and simultaneously provide an open interface to support unified management via the upper cloud platform.

**Comment by pooja** [comment]
We're closing this issue since it's been many months, but please reopen if desired
