### ISSUE TITLE
[rule proposal] Limit a team to a maximum of 5% rewards

### ISSUE THREAD

**Issue by KaptinLin** [filecoin-project/slingshot#429]
To ensure Slingshot achieves the competition's [goals](https://slingshot.filecoin.io/about)
`Preserve humanity's most important datasets on the Filecoin network. It has always been Filecoin's mission to serve as the foundation for humanity's information. With Slingshot, we are really excited to work with teams who are energized by that same mission so that, together, we can make this vision a reality! This includes telemetry and imaging datasets, historical archives, Creative Commons-licensed media and entertainment datasets, scientific research papers, and more!`

## Problem
Some datasets will be stored in a proportion of more than 10%, which is not conducive to Filecoin storing more datasets, just like Landsat 8 in the previous phase.

## Proposed Solution
Maximum rewards for any individual team will be 5% of the prize pool. In this way, some big players will not have too many advantages over small teams, so that more small teams will participate in the slingshot competition, and more different data sets will be saved in the Filecoin network.

Another way is to limit the same dataset to a maximum of 5% of the prize pool, so that the advantage of big players will be weakened. At the same time, there can be at least 20 datasets stored on the Filecoin network, and even more datasets. It is a great help to Filecoin achieving its mission.

**Comment by pooja** [comment]
Thanks for the suggestion @KaptinLin! I understand the spirit of where this is coming from, but I think there are unintended consequences to what you're suggesting. If we limit 5% rewards per dataset, this means that we'll end up with a lot of partial datasets on Filecoin, which is not what we want with Slingshot. It's also impossible to enforce a rule that tries to limit 5% rewards per team (it's very easy to create sybils by creating multiple accounts and one project per account). 

I think we can set a limit of 5-10% max rewards per project, down from a 20% limit per project in the prior round.

One other thing you should keep in mind is that all teams that particpate in Slingshot get something. It is not accurate to say that just the top 10 or 20 teams get rewards. Look at the data from the last round: https://docs.google.com/spreadsheets/u/1/d/1PQ43TplJRW17n5IvqcfNYdrwEXxNQeU4OdvIB46jO6U/edit#gid=0
