### ISSUE TITLE
[rule proposal] Rewards based on both data store and retrieval success rate

### ISSUE THREAD

**Issue by vht210** [filecoin-project/slingshot#431]
## Problem
Goal: 100% retrieval success rate
Rewards: Total data store
## Proposed Solution
Rewards should equal to Total_data_store*retrieval_success_rate/100
By enforce this, developer will focus on testing and selecting miners.
The final documentation should also contain  the result of testing retrievals data

**Comment by xinaxu** [comment]
The retrieval success rate is related to where the committee performs the retrieval. So if the retrieval tests are performed in one region, it is unfair to slingshotter who stores data in another region. A potential solution is to have the slingshotter mark the region of the miner so the committee can setup retrieval tests from different regions.

**Comment by pooja** [comment]
Thanks for the suggestion @vht210! We'll definitely be introducing retrieval success rate as a component of final rewards. While we're still finalizing how exactly this will work, we can publish some more information about this in the next couple weeks. I think @xinaxu brings up a good point regarding retrieval region and one idea is to have participants upload miner region for each deal as part of the final upload process.

**Comment by pooja** [comment]
We'll close this issue for now, since we'll be implementing a version of this for Slingshot 2.3
