### ISSUE TITLE
[rule proposal] Bring back the mandatory presentation from the top 10 projects at the closing ceremony.

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/slingshot#432]
Many of the top projects are from the same "filhub" organization - and are they really belong to different teams or is it one team? The presentation can at least let us know who they are and indeed are different people.

**Comment by KaptinLin** [comment]
I have contacted several projects introduced by filhub, they come from different regions. Similar to the service provided by filswan, I don’t think all the projects on filswan are from the same team.

**Comment by Huang-HU** [comment]
Thanks to Filhub's help, 
We can participate in the SR2.2 competition.
Willing to do a presentation in the closing celebration.

**Comment by pooja** [comment]
Thanks @kernelogic -- I think this is a good idea to bring back. For Slingshot 2.3 closing ceremony, we can reintroduce demo time for the top 10 projects! However, it's not fair for just the top 10 projects to have to produce these demo videos, so we'll make it a requirement for all projects.

These demos can include showing how the data for this project was processed by processing a sample file and then retrieving a file and opening it within the appropriate application to show the data and how it can be used by others.

**Comment by pooja** [comment]
We'll close this issue for now, since we'll be implementing this for Slingshot 2.3 judging for all teams
