### ISSUE TITLE
[rule proposal] all files in source (MD5SUMS) should be submitted .

### ISSUE THREAD

**Issue by qexcsd222** [filecoin-project/slingshot#433]
## Problem
We need to consider how Web3 App will integrate with [**slingshot datasets**](https://github.com/filecoin-project/slingshot/blob/master/datasets.md) in the future.
## Proposed Solution
new cid [CSV ](https://docs.google.com/spreadsheets/d/1xcI3XVwrH0cuVaQfEPPA06Csm1jJB3NNtlRqgDLMSOg/edit?usp=sharing) example template (PS: better way is to open up an API to submit it ) :
addition  column source_lists ([Md5sum Doc](https://en.wikipedia.org/wiki/Md5sum)) :
```
{
	"PieceName": "test.tar",
	"PieceSize": 23622320128,
	"Lists": [{
		"PathName": "test/subdir/test.md",
        "PathType":"file",
		"md5sum": "f4c6d12fc22ef3a2bf858bb387833498",
        "Size":255,
	}, {
		"PathName": "test/subdir2/subdir3/",// toomuch files we should put the dir here
         "PathType":"folder",
		 "md5sum": "f4c6d12fc22ef3a2bf858bb387833493",
         "Filecount":4700,
         "Size":23333333333,
	}, {
		"PathName": "test/subdir/test.md",
        "PathType":"file",
		"md5sum": "f4c6d12fc22ef3a2bf858bb387833492",
        "Size":2553,
	}]
}

```

**Comment by xinaxu** [comment]
Is it the MD5 of the original file or the car file. What if the car file contains multiple objects.

**Comment by qexcsd222** [comment]
[Md5sum Doc](https://en.wikipedia.org/wiki/Md5sum)

**Comment by pooja** [comment]
Thanks for the suggestion @qexcsd222. I'm not sure what problem this is trying to solve exactly. While I agree that an API would be nice for submission purposes, the current submission method works ok and we're not going to be able to make that change in time for Slingshot 2.3. Closing this issue out for now.
