### ISSUE TITLE
[rule proposal] CDN in each region for data trasfer cross continent

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/slingshot#434]
_Do you have an idea for how to ensure Slingshot achieves the competition's [goals](https://slingshot.filecoin.io/about)? 
In order to let the data can be retrieval globally from any place, the first step is transferring the original data to global content delivery network.Then the miners in different region can seal it.

## Problem
Teams in different region complaints about transfer between North America , China and Europe are too slow. If teams can transfer to other regions faster and stable, it will make the copies distributed in the world more balanced.
_

## Proposed Solution
Some teams are using AWS or Alicloud for miners in different region download it, which is expensive and paid to those  cloud networks. It is better to build several CDN network and pay to Filecoin miner community. NBFS Canada has design about it ,and would like to apply for a grant for this proposal.

Implementation Grant request: 1000 FIls
Implementation Time:  2 weeks
Goal: Build at least 3 node in North America, Europe and China. Transmission speed: >100 Mbits. Server Disk space : 20TB
Technology: Authenticated CDN server. IPFS gateway
Payment Method for CDN service: 0.002 Fil/GB for download, 0 for upload to CDN server.
 
We can provide more detailed implementation plan by requested.

**Comment by pooja** [comment]
Thanks @flyworker -- this doesn't seem like a rule proposal for Slingshot, but rather a grant proposal. If you haven't already, please consider submitting a dev grant proposal/application here: https://github.com/filecoin-project/devgrants (more info: grants.filecoin.io).
