### ISSUE TITLE
[rule proposal] More transparent and helpful competition result

### ISSUE THREAD

**Issue by xinaxu** [filecoin-project/slingshot#436]
## Problem
1. The slingshot slack community is having intense debate on the fairness of the competition result. Participants often feel unfair about the penalty incurred to them or the penalty that they believe should be imposed to others. 
2. Participants also want to learn about how they may improve in the next phase, for one example, how successful is the retrieval test. It is quite common that the retrieval is successful when the participants test it but does not work well with committee's Internet provider. For another example, how well is the documentation. The participants want to know any flaw or places to improve regarding the documentation.

## Proposed Solution
When announcing the competition result, also have below details to let participants informed as well as improve retrieval/documentation for the next phase.
1. Where and how the retrieval tests are performed and the result.
2. Comments on acquisition/retrieval documentation for future improvements
3. List of the rules the participant may have violated, how is it determined and what is the penalty
4. List of things that participant may have done great and should keep doing
5. Any other reasons for the penalty/rewards

**Comment by pooja** [comment]
This isn't a rule proposal, but it is a helpful suggestion. We'll consider what information to make available for Slingshot 2.3 final results, and try to make as much information available as possible. We will most likely introduce robust retrieval testing in this round, so at the very least, that information will be made available for Slingshot 2.3 judging.
