### ISSUE TITLE
[rule proposal] Limit or track changes to project names

### ISSUE THREAD

**Issue by orvn** [filecoin-project/slingshot#441]
### Problem

- Currently on the Slingshot website, there's no limitation to how many times a user can change their project's information
- Most project info is fine to change, but one field that creates confusion is the **project name**
- Because we're not tracking these, it is sometimes difficult to follow a project's participation over multiple phases (e.g., if it went by a different name, it isn't clear which rewards it collected in a past phase)

### Proposed Solution

Either

1. Allow only one change for a project name
_or_
2. Allow project name changes only by submitting a ticket to the development team, which must be manually approved

> Note that #2 is currently how we address project transference. If one user wants to transfer a project to another user, they have to reach out and manually request to do so.

**Comment by pooja** [comment]
Thanks for the suggestion @orvn! I think we should implement #2 -- do you need any help from us to make that change? We can happily include a message about that in the Slingshot website FAQs
