### ISSUE TITLE
[rule proposal] Add new curated dataset

### ISSUE THREAD

**Issue by EpiK-Tech** [filecoin-project/slingshot#442]
## Problem
[EpiK Protocol](epik-protocol.io) focuses on converting human knowledge into knowledge graph. We want to join Filecoin Slingshot and submit knowledge graph dataset. But we cannot find the knowledge graph dataset type.

## Proposed Solution
Slingshot could add a new curated dataset type named "knowledge graph dataset".

**Comment by pooja** [comment]
Hi @EpiK-Tech, can you please submit the link for this dataset? The hyperlink in the issue doesn't work

**Comment by orvn** [comment]
@pooja the link above was malformed, here is the corrected version: [epik-protocol.io](https://epik-protocol.io)

**Comment by pooja** [comment]
@EpiK-Tech this doesn't look like a public dataset. Where is the download link that anyone can use to download and store the same data for Slingshot? If it isn't fully public, it's not a good fit for Slingshot.

**Comment by dkkapur** [comment]
Hi @EpiK-Tech - just circling back to this! Can you share any more details on the public availability of the dataset and where it can be downloaded by anyone?

**Comment by dkkapur** [comment]
@EpiK-Tech - checking back on the above questions!

**Comment by dkkapur** [comment]
Closing this out for now. Please open a new issue in this repo if you'd like to propose this or a different dataset for Slingshot.
