### ISSUE TITLE
[Change Email] Slingshot 2.2 - IPFSCrawldata

### ISSUE THREAD

**Issue by gayeley** [filecoin-project/slingshot#443]
My old email:gayeley@163.com can't reach prizes@protocol.ai
I have changed my email address to Gmail (gayeley121@gmail.com) in slingshot, 
and resend my information to you (prizes@protocol.ai).

**Comment by pooja** [comment]
@orvn Could you please help to make this change if you haven't already? Thanks!

**Comment by orvn** [comment]
@pooja this has been completed and the email was successfully changed. I verified the information with `pkim` on the prizes team. Closing ticket.
