### ISSUE TITLE
Request to add public books dataset from archive.org

### ISSUE THREAD

**Issue by liuk9662** [filecoin-project/slingshot#448]
## Dataset being requested
Dataset Name: public books dataset
Dataset Description: A collection of public books to all for free downloading and reuse
Size: 
File Format: pdf
Link to Dataset: https://archive.org/details/books

**Comment by dkkapur** [comment]
Hi @liuk9662 - thanks for suggesting this dataset to be added to Slingshot! 

Just looked through the Internet Archive set that you linked - just to confirm, is your suggestion that the dataset would be an aggregation of pdfs from the set of books which are available for download? Therefore the size of the dataset would be dependent on the number of books downloaded by the particular client and stored on the network, correct?

**Comment by dkkapur** [comment]
@liuk9662 - just wanted to circle back on this and see if you had had the chance to review the above comment?

**Comment by liuk9662** [comment]
Sorry, I just came back to reply to this message

Yes, PDF files

Others have movies and small videos, but I think books should be more useful.

Can I use this dataset to participate in the new round of SR2 Slingshot competition?

**Comment by orvn** [comment]
@dkkapur, just wanted to mention you here. You might have not seen this last update to the ticket.

**Comment by dkkapur** [comment]
Thanks @orvn!

@liuk9662 - is there a specific subset of this dataset that you'd specifically want to target for onboarding onto Slingshot? 
Additionally, looks like most of these book files in pdf form are in the < 10 MB range. Is it fair to state that in order for them to qualify for Slingshot, there should be a clear path for users to retrieve specific book files through the Deal UI for your project as well as by following the documentation you will publish?

**Comment by dkkapur** [comment]
Closing this out for now - we can reopen for reconsidering for 2.7 if required. Thanks.
