### ISSUE TITLE
Add Filecoin slack handle for Mike Goelzner - community reviewer

### ISSUE THREAD

**Issue by dineshshenoy** [filecoin-project/slingshot#45]

**Comment by dineshshenoy** [comment]
"Mike - Protocol Labs"

**Comment by pooja** [comment]
Quick note, name is Mike Goelzer (no "n") in last name, in case you're having trouble finding him

**Comment by dineshshenoy** [comment]
https://github.com/filecoin-project/slingshot/pull/67
