### ISSUE TITLE
[dataset request] Open Library Data Dump

### ISSUE THREAD

**Issue by aditsachde** [filecoin-project/slingshot#456]
## Dataset being requested
Dataset Name: Open Library Data Dump
Dataset Description: This dataset includes records of over 22 million works, 30 million editions and 8 million authors, curated by the Open Library project.
Size: ~50G uncompressed, ~10G compressed
File Format: TXT
Link to Dataset: https://openlibrary.org/data/ol_dump_latest.txt.gz

**Comment by orvn** [comment]
For reference, this is the [dataset information page](https://openlibrary.org/data) from Open Library's website

**Comment by dkkapur** [comment]
@aditsachde - quick clarifying question: this dataset is the actual JSON dump of the entire set of records correct? Is the use case here to help make IA's catalog easier to access?

**Comment by aditsachde** [comment]
Yep, it's all the JSON records that OpenLibrary has (i.e. book metadata, not the actual books). I'm using the dataset in another [project](https://github.com/aditsachde/ipld-distributed-datasets) based on IPFS/IPLD.

Downloading the dataset directly from the IA is extremely slow right now (>4 hours to download 10GB), so having it on the Filecoin network would go a long way in making it easier to access.

**Comment by dkkapur** [comment]
@aditsachde - sounds good - thank you. I think we'll move forward with adding this to the Slingshot eligible datasets! Kicking off a PR now to the official list and then will have the website updated shortly after.

**Comment by dkkapur** [comment]
Closing this one out since it was added to the set of qualifying datasets!
