### ISSUE TITLE
Decide on miner structure (json vs. text) and standardize location/endpoint

### ISSUE THREAD

**Issue by dineshshenoy** [filecoin-project/slingshot#46]
Capturing here for discussion.   Debate on the optimal approach for available miners for slingshot.   Current approach is 3 text files, but a json file maybe easier for like the following:

{
	"buckets": [{
		"name": "North America",
		"amount": 1,
                "minerAddresses": ["t09833"]
	}, {
		"name": "Europe",
		"amount": 1,
		"minerAddresses": ["t02620"]
	}
}

cc: @jsign @ribasushi

**Comment by jsign** [comment]
I think this issue was created after my last comment [here](https://github.com/filecoin-project/slingshot/pull/39).
For Powergate, as for any other application wanting to use this list, a more structured format as JSON I think is more convinient.

**Comment by dineshshenoy** [comment]
Moving forward with json and /miners.json
