### ISSUE TITLE
[dataset extension request] 3000 Rice Genomes

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/slingshot#461]
_You can request to continue uploading an incompletely onboarded dataset to Slingshot if it previously qualified for rewards but no longer does per the list of [curated datasets for Slingshot](https://github.com/filecoin-project/slingshot/blob/master/datasets.md). Please note that these requests will be reviewed on a case by case basis and approvals are only for specific project teams to continue onboarding the specific dataset._

## Slingshot participation information
- Dataset Name: 3000 Rice Genomes
- Project team name: Kernelogic
- Phase(s) in which dataset was onboarded by the project team: 2.4, 2.5

## Dataset onboarding progress
- Total amount of CIDs to onboard the total dataset: 3551
- Amount of CIDs outstanding / not yet onboarded in deals: 2409 (up till the end of phase 2.5).
- Link to gist/hackmd/textfile listing the remaining CIDs: https://gist.github.com/kernelogic/df8b3244535db5406cf7f10e83f900be
- Number of deals made so far: 5609 (up till the end of phase 2.5).
- Number of deals expected to be made (include replicas stored with unique miner IDs): 10000
- Approx. number of weeks required to onboard the rest of the dataset: 4 weeks

## Notes
I have made a lot efforts to get a LDN and communicate with MinerX members to do these deals. I appreciate if I can get an extension to allow me finish onboarding the whole set of data and fully utilize the LDN.

**Comment by kernelogic** [comment]
All my data is stored in their raw format. Non-tar-ed.

**Comment by dkkapur** [comment]
@kernelogic thanks for sharing this level of detailed information! Approving this one for Phase 2.6. Dataset information is updated for your project details here: https://slingshot.filecoin.io/project/604a884ba191de6cd9228525

**Comment by kernelogic** [comment]
Thank you very much @dkkapur !

**Comment by orvn** [comment]
@kernelogic, your project [Kernelogic Rice Genomes](https://slingshot.filecoin.io/project/604a884ba191de6cd9228525) has been added as an exception, and you can now switch to the `3000 Rice Genomes Project` dataset within the current phase (2.5).

cc @dkkapur
