### ISSUE TITLE
[dataset extension request] for  Top 100 Crypto Investor Dataset

### ISSUE THREAD

**Issue by georgemac510** [filecoin-project/slingshot#466]
_You can request to continue uploading an incompletely onboarded dataset to Slingshot if it previously qualified for rewards but no longer does per the list of [curated datasets for Slingshot](https://github.com/filecoin-project/slingshot/blob/master/datasets.md). Please note that these requests will be reviewed on a case by case basis and approvals are only for specific project teams to continue onboarding the specific dataset._

## Slingshot participation information
- Dataset Name: Top 100 Crypto Investor Dataset
- Project team name: Fin-File-Crypto
- Phase(s) in which dataset was onboarded by the project team: 2.1, 2.2, 2.3, 2.4, 2.5, 2.7

## Dataset onboarding progress
- Total amount of CIDs to onboard the total dataset:  ~1100
- Amount of CIDs outstanding / not yet onboarded in deals: ? Please see at bottom.
- Link to gist/hackmd/textfile listing the remaining CIDs:  https://docs.google.com/spreadsheets/d/1qGtYovqTozWtO5n_UGiS2iL8566RUYJ5gUj2WKmSgjs/edit?usp=sharing

- Number of deals made so far: 635
- Number of deals expected to be made (include replicas stored with unique miner IDs): ~450
- Approx. number of weeks required to onboard the rest of the dataset: ~9

Some of these questions may not be applicable to Top 100 Crypto Investor Dataset or very difficult to define as the dataset is updated on a daily basis with timely and actionable investment data. The dataset does not have a finite number of files or CIDs.

**Comment by orvn** [comment]
@georgemac510: Just to confirm, you're asking for extension into phase 2.7 (not 2.6, which concluded recently), is that correct?

**Comment by georgemac510** [comment]
Hi @orvn That is correct. I want to extend to the end of 2.7. Thanks!

**Comment by orvn** [comment]
cc @dkkapur to review

**Comment by georgemac510** [comment]
@dkkapur Can you take a look at this issue? Thanks.

**Comment by dkkapur** [comment]
Approving this. Thanks @georgemac510. 

@orvn let's add this dataset for team "Fin-File-Crypto".

**Comment by georgemac510** [comment]
Thanks @dkkapur and @orvn

**Comment by orvn** [comment]
@georgemac510: you should now be able to select this dataset from your Account page on the Slingshot site (make sure you select the `current` phase, 2.7, from the dropdown).
