### ISSUE TITLE
[dataset extension request] Smartcity 

### ISSUE THREAD

**Issue by xingjitansuo** [filecoin-project/slingshot#467]
_You can request to continue uploading an incompletely onboarded dataset to Slingshot if it previously qualified for rewards but no longer does per the list of [curated datasets for Slingshot](https://github.com/filecoin-project/slingshot/blob/master/datasets.md). Please note that these requests will be reviewed on a case by case basis and approvals are only for specific project teams to continue onboarding the specific dataset._

## Slingshot participation information
- Dataset Name: Smartcity- Sensor-based network and data analysis system
- Project team name: XingjiTanSuo-smartcity
- Phase(s) in which dataset was onboarded by the project team:  2.2, 2.3, 2.4

## Dataset onboarding progress
- Total amount of CIDs to onboard the total dataset: 24017
- Amount of CIDs outstanding / not yet onboarded in deals: 23558
- Link to gist/hackmd/textfile listing the remaining CIDs:
- Number of deals made so far: 459
- Number of deals expected to be made (include replicas stored with unique miner IDs): 80000
- Approx. number of weeks required to onboard the rest of the dataset: 8

**Comment by orvn** [comment]
@xingjitansuo: Are you asking for extension into phase 2.6 (which concluded recently) or phase 2.7?

**Comment by xingjitansuo** [comment]
@orvn, for phase 2.7.

**Comment by xingjitansuo** [comment]
@dkkapur is there any update here ?

**Comment by dkkapur** [comment]
@xingjitansuo - approving this one. 

@orvn can we enable this dataset for project team "XingjiTanSuo-smartcity"

**Comment by orvn** [comment]
@xingjitansuo is your project name `Smartcity- Sensor-based network and data analysis system`? 
We couldn't find that, but did find: `Smartcity- Sensor-based network and data analysis system`? ([link to project](https://slingshot.filecoin.io/project/5fd1d76344b446c952f583b2))

Is that the right one?

**Comment by dkkapur** [comment]
@xingjitansuo - just looked through the past conversations on this dataset and it looks like we did not get the full context on this dataset. Can you help me with:
- who is generating the dataset?
- who is paying for the data to be collected today?
- is it available for a free download somewhere on the web today?
- what city or cities is the data being captured in?

**Comment by dkkapur** [comment]
Pending response to above questions before approving.

**Comment by xingjitansuo** [comment]
> @xingjitansuo is your project name `XingjiTanSuo-smartcity`? We couldn't find that, but did find: `Smartcity- Sensor-based network and data analysis system`? ([link to project](https://slingshot.filecoin.io/project/5fd1d76344b446c952f583b2))
> 
> Is that the right one?

Correct

**Comment by xingjitansuo** [comment]
> 
- who is generating the dataset?
   Those datasets are generated by a research lab in University of Electronic Science and Technology of China. 
- who is paying for the data to be collected today?
   University Research Fund. 
- is it available for a free download somewhere on the web today?
   Yes, you could access from http://api.sr2.glm2m.com/index.php?r=smartcity-dataset%2Fdataset
- what city or cities is the data being captured in?
   Most of the data are captured in Sichuan - China.

**Comment by orvn** [comment]
Thanks for the reply @xingjitansuo.

I had some more questions and concerns with issues I've been having with your app UI.

1. Did something change with the app? Last week I was able to download files successfully (`.wav` files). However now I get `.db`  files. Is it just a mime type issue or something else?

2. I’m also getting some 503 when making requests occasionally  
![Slingshot 2021-12-13 at 23 50 42](https://user-images.githubusercontent.com/3689720/145935508-443af8b8-2ceb-4359-9608-4af810213ef1.png)
3. In order to work for Slingshot, these datasets need to be **easily accessible by other participants**. Is there a way for a user to download the fully dataset from you app? (either as one download or just a few chunks?)

**Comment by xingjitansuo** [comment]
That is a good call out. The server was down and it has now been fixed. Please check one more time. Those datasets are open to public and is accessible by clicking download button shown in the website. @orvn

**Comment by orvn** [comment]
@xingjitansuo: it seems to mostly work now, two issues I'm finding:

- I am unable to download the dataset: `数据集下载 (Dataset Download)` does not trigger a download

- Some files still don't seem to download in the correct format: I'm downloading `920.wav` from the `校园 (Campus)` tab here, but it still returns a `.db` file. May other files do work however.


![db](https://user-images.githubusercontent.com/3689720/146584617-c1add404-7c7f-41a3-b0f8-845599e67654.png)

![dataset-download](https://user-images.githubusercontent.com/3689720/146585089-a39ae691-15ae-4efc-8614-61f51fdaaaed.png)

**Comment by xingjitansuo** [comment]
@orvn, 
1. 数据集下载 (Dataset Download) returns the static page where you can find all the wav files. This page does not support batch download. If one is interested in specific file,  could simply hit the download button near the wav file.
2. We expect this db file format error to happen occasionally.  Since this dataset is normally used within a small group, it is not worth to check every file format.

**Comment by orvn** [comment]
> This page does not support batch download

Does this mean that other participants can't download the full dataset (without running a script that scrapes your app UI)? @xingjitansuo 

Because that would be a blocker to _other_ participants using this dataset, since Slingshot users will normally try to fill 32 GiB sectors.

**Comment by xingjitansuo** [comment]
@orvn I talked to the team, and they provided the batch download features specifically for onboarding to Filecoin.

**Comment by orvn** [comment]
I tested the download from the list and it works, but the list needs some slight modification. 

All files have an extra `/` character in the URI constructor. Please fix this @xingjitansuo.

I ran a test on all 24k of your records when it's removed and they _do_ download successfully.
```
...
http://117.175.0.137/nfs/179//B3/data2/883.wav
http://117.175.0.137/nfs/179//B3/data2/898.wav
http://117.175.0.137/nfs/179//B3/data2/949.wav
http://117.175.0.137/nfs/179//B3/data2/932.wav
...
```

To make it easier for other Slingshot users, I also think there should be a command that helps them download all files.. @dkkapur, does that make sense to you? 

A simple *nix-friendly version with no dependencies would look something like:

```zsh
curl -s http://117.175.0.137/down.downlist\?id\=1 | xargs -L1 -I {} curl -O {}
```

**Comment by xingjitansuo** [comment]
@orvn 
Please check again.  :)

**Comment by dkkapur** [comment]
@xingjitansuo - let's proceed with approving this for current and future phases for now. Thanks for your hard work in making it available easily to others as well!

**Comment by xingjitansuo** [comment]
Thanks for all  your effort ! @dkkapur @orvn

**Comment by orvn** [comment]
@xingjitansuo, you will find that your project is able to select the Smart City dataset. 

@dkkapur, for now, I added it to the temporarily disallowed dataset, but if needed, you can move it up as a dataset available for everyone on the next phase at your discretion.

**Comment by orvn** [comment]
@xingjitansuo, [the app URL](http://api.sr2.glm2m.com/index.php?r=smartcity-dataset%2Fdataset) appears to be down? Is this just temporary?

**Comment by xingjitansuo** [comment]
@orvn  I synced up with the team, and it should be alive next week.

**Comment by orvn** [comment]
Sounds good, thanks!
