### ISSUE TITLE
[dataset request] Next Generation Weather Radar

### ISSUE THREAD

**Issue by boqian-nbai** [filecoin-project/slingshot#469]
_You can request to add a new dataset to the list of [curated datasets for Slingshot](https://github.com/filecoin-project/slingshot/blob/master/datasets.md). Datasets must be fully public, no proprietary datasets or datasets that require a login are allowed._

## Dataset to be added to Slingshot
Dataset Name: NEXRAD - Next Generation Weather Radar

Dataset Description: Real-time and archival data from the Next Generation Weather Radar (NEXRAD) network

Size:2 PiB

File Format:

Link to Dataset download: https://registry.opendata.aws/noaa-nexrad/

**Comment by orvn** [comment]
@boqian-nbai did you close this intentionally?
