### ISSUE TITLE
[dataset request] NEXRAD

### ISSUE THREAD

**Issue by mikesiwer** [filecoin-project/slingshot#470]
_You can request to add a new dataset to the list of [curated datasets for Slingshot](https://github.com/filecoin-project/slingshot/blob/master/datasets.md). Datasets must be fully public, no proprietary datasets or datasets that require a login are allowed._

## Dataset to be added to Slingshot
Dataset Name: NEXRAD - Next Generation Weather Radar

Dataset Description: The Next Generation Weather Radar (NEXRAD) system is a network of 160 high-resolution S-band Doppler weather radars jointly operated by the National Weather Service (NWS), the Federal Aviation Administration (FAA), and the U.S. Air Force. The NEXRAD system detects precipitation and wind, and its data can be processed to map precipitation patterns and movement. NCEI provides access to archived NEXRAD Level-II data and Level-III products.

Size: 2 PiB

File Format: Various

Link to Dataset download: https://registry.opendata.aws/noaa-nexrad/

**Comment by dkkapur** [comment]
@mikesiwer - are you interested in storing this dataset still? Happy to approve if so, meets the needs.

**Comment by orvn** [comment]
(ping @mikesiwer)

**Comment by mikesiwer** [comment]
> @mikesiwer - are you interested in storing this dataset still? Happy to approve if so, meets the needs.

Yes! I am still interested.

**Comment by dkkapur** [comment]
Cool - will approve this for Phase 2.8 and onwards.

**Comment by orvn** [comment]
Added for 2.8!
