### ISSUE TITLE
[documentation] small typo? miner_country mentioned

### ISSUE THREAD

**Issue by jsmetana** [filecoin-project/slingshot#471]
Just thought to mention this, it seemed odd to me:

![image](https://user-images.githubusercontent.com/29602127/147150326-76d17c18-6766-4d1a-8402-da6a0f60f80b.png)

Sorry if this has a reason I'm not aware of, or if it's something _really not important_.

**Comment by orvn** [comment]
Thanks for reporting, we'll be removing the `miner_country` field from the docs. In the meantime you can just submit the `csv` as specified on the upload area (log in to your account and select a project that participated in a particular phase).

**Comment by orvn** [comment]
@jsmetana, this is now resolved (`miner_country` was removed from the docs as a requirement)
