### ISSUE TITLE
Add instructions on how to add a new miner.

### ISSUE THREAD

**Issue by dineshshenoy** [filecoin-project/slingshot#48]

**Comment by jsign** [comment]
Some notes:
- Should be reachable, that's to say: there should be a confirmation that `lotus client query-ask t0XXXX` is successful.
- It should have some power in the network.

**Comment by jsign** [comment]
Another point, miners should be told that the price per epoch should be something below X to make sense for people having funds of 0.25FIL as planned.

**Comment by dineshshenoy** [comment]
Also remove the miners/ folder

**Comment by dineshshenoy** [comment]
https://github.com/filecoin-project/slingshot/pull/69

**Comment by dineshshenoy** [comment]
Merged: https://github.com/filecoin-project/slingshot/pull/69
