### ISSUE TITLE
[dataset request] Earth Observation Data Cubes for Brazil

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/slingshot#526]
## Dataset to be added to Slingshot
Dataset Name: Earth Observation Data Cubes for Brazil

Dataset Description: Earth observation (EO) data cubes produced from analysis-ready data (ARD) of CBERS-4, Sentinel-2 A/B and Landsat-8 satellite images for Brazil. The datacubes are regular in time and use a hierarchical tiling system.

Size: 112.9 TiB

File Format: tif

Link to Dataset download: https://registry.opendata.aws/brazil-data-cubes/

**Comment by dkkapur** [comment]
@kernelogic can you help me understand what subset of this dataset is landsat-8 vs the others? In case you have that, would be good to understand so we can also look at overlap with landsat-8 datasets onboarded in the past through Slingshot.

**Comment by dkkapur** [comment]
Looks like this dataset groups images based on geographic coordinates and adds on additional useful data on it. Based on this, let's move forward with including this. Thank you @kernelogic.

**Comment by orvn** [comment]
Adding this, but under the official dataset name from [the original source](http://brazildatacube.org/en/home-page-2/#dataproducts), "Brazil Data Cube"
