### ISSUE TITLE
[dataset request] Terra Fusion Data Sampler

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/slingshot#527]
## Dataset to be added to Slingshot
Dataset Name: Terra Fusion Data Sampler

Dataset Description: The Terra Basic Fusion dataset is a fused dataset of the original Level 1 radiances from the five Terra instruments. 

Size: 136.2 TiB

File Format: h5

Link to Dataset download: https://registry.opendata.aws/terrafusion/

**Comment by orvn** [comment]
Added for 2.8!
