### ISSUE TITLE
[dataset request] NASA NEX

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/slingshot#528]
## Dataset to be added to Slingshot
Dataset Name: NASA NEX

Dataset Description: A collection of Earth science datasets maintained by NASA, including climate change projections and satellite images of the Earth's surface.

Size: 55.9 TiB

File Format: various

Link to Dataset download: https://registry.opendata.aws/nasanex/
https://github.com/awslabs/open-data-docs/tree/main/docs/nasa-nex

**Comment by dkkapur** [comment]
Good find, thanks @kernelogic!

**Comment by orvn** [comment]
Added for 2.8!
