### ISSUE TITLE
[dataset extension request] Top 100 Crypto Investor Dataset

### ISSUE THREAD

**Issue by georgemac510** [filecoin-project/slingshot#529]
**Slingshot participation information**
Dataset Name: Top 100 Crypto Investor Dataset
Project team name: Fin-File-Crypto
Phase(s) in which dataset was onboarded by the project team: 2.1, 2.2, 2.3, 2.4, 2.5, 2.7
Dataset onboarding progress
Total amount of CIDs to onboard the total dataset: ~900

Amount of CIDs outstanding / not yet onboarded in deals: ? Please see at bottom.

Link to gist/hackmd/textfile listing the remaining CIDs: https://docs.google.com/spreadsheets/d/1qGtYovqTozWtO5n_UGiS2iL8566RUYJ5gUj2WKmSgjs/edit?usp=sharing

Number of deals made so far: ~810

Number of deals expected to be made (include replicas stored with unique miner IDs): ~400

Approx. number of weeks required to onboard the rest of the dataset: ~9

Some of these questions may not be applicable to Top 100 Crypto Investor Dataset or very difficult to define as the dataset is updated on a daily basis with timely and actionable investment data. The dataset does not have a finite number of files or CIDs.

**Comment by dkkapur** [comment]
I'm OK with supporting this. Makes sense that underlying dataset grows, and list of CIDs is hard to nail down completely.

**Comment by dkkapur** [comment]
@orvn @timelytree can we approve this project in the backend?

**Comment by dkkapur** [comment]
@georgemac510 we may need the client address with which you are making deals too, just in case, can you share that ASAP?

**Comment by georgemac510** [comment]
@dkkapur @orvn @timelytree The FIL address for the client is:  f3woyrzyn634jgelyt4tj4hzw7mp7lxpacxbvaav3f7jnb4jrowjzl4mjadlpxgvxdiu36w23fzlizc5vs2bqa
The URL for the client is: https://fin-crypto.onrender.com/
Thanks for the approval.

**Comment by georgemac510** [comment]
Hi @dkkapur @orvn @timelytree It appears that `Top 100 Crypto Investor Dataset` was never moved back to a "qualifying dataset". Had this ever been finally approved for Slingshot 2.8 and Slingshot 3.0?

**Comment by orvn** [comment]
@georgemac510, sorry about that, I was OOO when this request came in and missed this notification. Your project has been added as an exception for this phase!
