### ISSUE TITLE
[dataset extension request] SmartCity Dataset

### ISSUE THREAD

**Issue by xingjitansuo** [filecoin-project/slingshot#530]
_You can request to continue uploading an incompletely onboarded dataset to Slingshot if it previously qualified for rewards but no longer does per the list of [curated datasets for Slingshot](https://github.com/filecoin-project/slingshot/blob/master/datasets.md). Please note that these requests will be reviewed on a case by case basis and approvals are only for specific project teams to continue onboarding the specific dataset._

## Slingshot participation information
- Dataset Name: SmartCity Sensor-based network and data analysis system
- Project team name: xingjitansuo 
- Phase(s) in which dataset was onboarded by the project team: 2.7

## Dataset onboarding progress
- Total amount of CIDs to onboard the total dataset:  25000
- Amount of CIDs outstanding / not yet onboarded in deals: 5000
- Link to gist/hackmd/textfile listing the remaining CIDs:
- Number of deals made so far: 11408
- Number of deals expected to be made (include replicas stored with unique miner IDs):  20000
- Approx. number of weeks required to onboard the rest of the dataset: 8

**Comment by xingjitansuo** [comment]
[smartcity-CID.txt](https://github.com/filecoin-project/slingshot/files/8629588/smartcity-CID.txt)

**Comment by orvn** [comment]
Hi @xingjitansuo, sorry about the late reply here. How many of these CIDs have you stored already vs how many are left to complete the dataset?

**Comment by xingjitansuo** [comment]
@orvn 
Currently, all the CIDs should be onboarded to the network.

**Comment by orvn** [comment]
Of these, how many (what approximate percentage) were onboarded in this most recent phase? (`2.8`) @xingjitansuo

**Comment by xingjitansuo** [comment]
100%. As I re-propose all the deals again in this new phase.
