### ISSUE TITLE
[dataset request] Terra Fusion Data Sampler

### ISSUE THREAD

**Issue by CodeIsLaw0108** [filecoin-project/slingshot#533]
_You can request to add a new dataset to the list of [curated datasets for Slingshot](https://github.com/filecoin-project/slingshot/blob/master/datasets.md). Datasets must be fully public, no proprietary datasets or datasets that require a login are allowed._

## Dataset to be added to Slingshot
Dataset Name: Terra Fusion Data Sampler

Dataset Description: The Terra Basic Fusion dataset is a fused dataset of the original Level 1 radiances from the five Terra instruments.

Size: 136.2 TiB

File Format: hdf

Link to Dataset download: https://registry.opendata.aws/terrafusion/

**Comment by CodeIsLaw0108** [comment]
Hi，It's first time for applying， Please let me know if any info loss on it

**Comment by dkkapur** [comment]
Hi - this was just added for Phase 2.8. See this for more info: https://github.com/filecoin-project/slingshot/issues/527. Please reopen if this was intended to be something different.
