### ISSUE TITLE
Dataset state change request - Human PanGenomics Project

### ISSUE THREAD

**Issue by liuziba** [filecoin-project/slingshot#541]
## Dataset information

- **Dataset name:** Human PanGenomics Project
- **Dataset state:** 
    - [ ] "CAR generation complete"
    - [x] Not Started
- **Your handle on Filecoin Slack:** Xinan Xu

> _We may contact you on Github or on Slack to confirm information_

 ## Change requested
  
- **Correct dataset state:**  
  - [x] "Remove"
  - [ ] "Not started"
  - [ ] "Downloading dataset"
  - [ ] "CAR generation in progress"  
  
 - **Why is this change being requested?:** I'm being too aggressive and claimed a dataset that I don't think I'd be able to complete. Want to remove this dataset and work on something that is easier.

**Comment by dkkapur** [comment]
![image](https://user-images.githubusercontent.com/2343218/178866663-a9d90462-2128-401e-b9ac-f5dce5898327.png)

Removed you from this dataset and it is now open to other DPs for claiming!
