### ISSUE TITLE
[v3] Two of my datasets cant be directly mounted with goofys as suggested by the guidelines

### ISSUE THREAD

**Issue by benjaminh83** [filecoin-project/slingshot#543]
## Purpose of this GitHub issue
* [ ] Issue with Slingshot deal engine
* [x] Issue with AWS Buckets
* [ ] Feedback for program design

## Description 
We are not able to mount the following datasets directly with goofys: 
- coupled-model-intercomparison-project-6, size 1.66 PiB, region us-west-2, file count 40,584,114
- encyclopedia-of-dna-elements-encode, size 1014.2 TiB, region us-west-2, file count 1,220,750

The third dataset (covid-19-genome-sequence-dataset, size 1.1 PiB, region us-east-1, file count 10,245,257) works fine with goofys. 
 
## Urgency/priorization 
* [ ] Low: non-blocking, nice to have
* [x] Medium: non-blocking, eventually must have
* [ ] High: blocking (i.e., I cannot get deal proposals when expected)

**Comment by liuziba** [comment]
@benjaminh83 could you try this patch?
https://github.com/liuziba/goofys/commit/fe378e8b6205e1afc6a32b449838a07578e31410

**Comment by dkkapur** [comment]
@benjaminh83 did this work for you?

**Comment by benjaminh83** [comment]
@liuziba @dkkapur Sorry for not getting back on this. So we ended up deciding not to use Goofys and just use native S3 instead.
