### ISSUE TITLE
Dataset state change request - Copernicus Digital Elevation Model (DEM)

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/slingshot#545]
## Dataset information

- **Dataset name:** Copernicus Digital Elevation Model (DEM)
- **Dataset state:** 
    - [x] Available
- **Your handle on Filecoin Slack:** rob

> _We may contact you on Github or on Slack to confirm information_

 ## Change requested
  
- **Correct dataset state:**  
  - [ ] "Not started"
  - [ ] "Downloading dataset"
  - [X] "CAR generation in progress"  
  
 - **Why is this change being requested?:** `can not select more than 3 datasets - 2 are already done, 1 is broken`

**Comment by justanothersynth** [comment]
@RobQuistNL looks like this dataset is already claimed!

<img width="882" alt="Screen Shot 2022-07-26 at 9 37 17 AM" src="https://user-images.githubusercontent.com/11708190/181019546-5453ed5c-f10a-420e-9c7e-c16b6a7c82a1.png">

**Comment by justanothersynth** [comment]
Closing because this dataset was claimed by someone else before I could assign it to @RobQuistNL
