### ISSUE TITLE
Dataset state change request - Deutsche Boerse Public Dataset

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/slingshot#547]
## Dataset information

- **Dataset name:** Deutsche Boerse Public Dataset
- **Dataset state:** 
    - [x] Available
- **Your handle on Filecoin Slack:** rob

> _We may contact you on Github or on Slack to confirm information_

 ## Change requested
  
- **Correct dataset state:**  
  - [ ] "Not started"
  - [ ] "Downloading dataset"
  - [X] "CAR generation in progress"  
  
 - **Why is this change being requested?:** `can not select more than 3 datasets - 2 are already done, 1 is broken`

**Comment by justanothersynth** [comment]
@RobQuistNL this dataset has been assigned to you and its state has been set to `CAR generation in progress` 🚀

**Comment by RobQuistNL** [comment]
@timelytree this dataset is no longer public;

```
aws s3 ls deutsche-boerse-xetra-pds

An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```

```
aws s3 ls deutsche-boerse-eurex-pds

An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```
