### ISSUE TITLE
Dataset state change request - KITTI Vision Benchmark Suite

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/slingshot#548]
## Dataset information

- **Dataset name:** KITTI Vision Benchmark Suite
- **Dataset state:** 
    - [x] Available
- **Your handle on Filecoin Slack:** rob

> _We may contact you on Github or on Slack to confirm information_

 ## Change requested
  
- **Correct dataset state:**  
  - [ ] "Not started"
  - [ ] "Downloading dataset"
  - [X] "CAR generation in progress"  
  
 - **Why is this change being requested?:** `can not select more than 3 datasets - 2 are already done, 1 is broken`

**Comment by justanothersynth** [comment]
@RobQuistNL this dataset has been assigned to you and its state has been set to `CAR generation in progress` 🚀
