### ISSUE TITLE
Dataset state change request - ECMWF ERA5 Reanalysis

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/slingshot#549]
## Dataset information

- **Dataset name:** ECMWF ERA5 Reanalysis
- **Dataset state:** 
    - [x] Available
- **Your handle on Filecoin Slack:** rob

> _We may contact you on Github or on Slack to confirm information_

 ## Change requested
  
- **Correct dataset state:**  
  - [ ] "Not started"
  - [ ] "Downloading dataset"
  - [X] "CAR generation in progress"  
  
 - **Why is this change being requested?:** `can not select more than 3 datasets - 4 are already done, 2 are broken`

**Comment by justanothersynth** [comment]
@RobQuistNL this dataset has been assigned to you and its state has been set to `CAR generation in progress` 🚀
