### ISSUE TITLE
Dataset state change request - Global Seasonal Sentinel-1 Interferometric Coherence and Backscatter Data Set

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/slingshot#551]
## Dataset information

- **Dataset name:** Global Seasonal Sentinel-1 Interferometric Coherence and Backscatter Data Set
- **Dataset state:** 
    - [x] Available
- **Your handle on Filecoin Slack:** rob

> _We may contact you on Github or on Slack to confirm information_

 ## Change requested
  
- **Correct dataset state:**  
  - [ ] "Not started"
  - [ ] "Downloading dataset"
  - [X] "CAR generation in progress"  
  
 - **Why is this change being requested?:** `can not select more than 3 datasets - 4 are already done, 2 are broken`

**Comment by justanothersynth** [comment]
@RobQuistNL this dataset has been assigned to you and its state has been set to `CAR generation in progress` 🚀

**Comment by RobQuistNL** [comment]
@timelytree while packing this one, the last .car file failed;

```
│   86    │ '62e17410e8f0d06de33fd6f1' │  86   │   'error'   │                                                               │                                                                    │             │             │ "EACCES: permission denied, copyfile '/storage0/slingshotv3/mnt/global-seasonal-sentinel-1-interferometric-coherence-and-backscatter-data-set/inventory/sentinel-1-global-coherence-earthbigdata/s3-inventory-sentinel-1-global-coherence-earthbigdata/2021-09-15T00-00Z/manifest.checksum' -> '/storage0/slingshotv3/temp/1dd21d8c-4b77-4f3a-b1d4-dd3f51ae45bc/inventory/sentinel-1-global-coherence-earthbigdata/s3-inventory-sentinel-1-global-coherence-earthbigdata/2021-09-15T00-00Z/manifest.checksum'" │
```

so I can not completele this set

**Comment by justanothersynth** [comment]
@RobQuistNL is this due to a Singularity issue?

**Comment by RobQuistNL** [comment]
Don't think so. But its been mentioned in the slack before;

https://filecoinproject.slack.com/archives/C01AZP8BKRQ/p1658803944553379
