### ISSUE TITLE
Dataset state change request - Cancer Genome Characterization Initiatives - Burkitt Lymphoma, HIV+ Cervical Cancer

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/slingshot#558]
## Dataset information

- **Dataset name:** Cancer Genome Characterization Initiatives - Burkitt Lymphoma, HIV+ Cervical Cancer
- **Dataset state:** 
    - [x] Available
- **Your handle on Filecoin Slack:** rob

> _We may contact you on Github or on Slack to confirm information_

 ## Change requested
  
- **Correct dataset state:**  
  - [ ] "Not started"
  - [ ] "Downloading dataset"
  - [X] "CAR generation in progress"  
  
 - **Why is this change being requested?:** `can not select more than 3 datasets - 8 are already done, 2 are broken`

**Comment by justanothersynth** [comment]
Closing with no action as this was claimed by someone else before I could get to it
