### ISSUE TITLE
non-existent github user with 3 datasets

### ISSUE THREAD

**Issue by marostelka** [filecoin-project/slingshot#576]
## Purpose of this GitHub issue
* [x] Issue with Slingshot ~~deal engine~~
* [ ] Feedback for program design

## Description 
User MarlineGFox has 3 datasets allocated:
- NOAA Atmospheric Climate Data Records (7.25 TiB)
- ISERV (4.9 TiB)
- IDEAM - Colombian Radar Network (8.7 TiB)

but I can't find him on github: (API: [MarlineGFox](https://api.github.com/users/MarlineGFox))
![image](https://user-images.githubusercontent.com/69842009/188285844-248e0504-256a-46de-bc66-2317db5a9fcc.png)

## Urgency/priorization 
* [ ] Low: non-blocking, nice to have
* [x] Medium: non-blocking, eventually must have
* [ ] High: blocking (i.e., I cannot get deal proposals when expected)

**Comment by orvn** [comment]
Hmm, I'm not finding this user by their [Github UID number](https://api.github.com/user/109978538) either. It's possible the account was deleted or removed. I'll double check to make sure that's actually the case.
