### ISSUE TITLE
Add miners to repo list

### ISSUE THREAD

**Issue by dineshshenoy** [filecoin-project/slingshot#79]
t01278 North America  (stuberman)
t014409 North america (monster)

**Comment by jennijuju** [comment]
test

**Comment by Meatball13** [comment]
Miner ID: t014409  North America (Meatball)

**Comment by sdm101** [comment]
Miner ID: t021069 North America (Brian Y)

**Comment by yablu** [comment]
t08403 Europe (TippyFlits)

**Comment by inickzen** [comment]
MinerID: **t022352**
Location: **Norway, Asker**
Slack: **Reiers**

_- TechHegde_

**Comment by cwhiggins** [comment]
t015927    North America    Chris

**Comment by nad010286** [comment]
t01238 ASIA (Filecoin-Vietnam)

**Comment by bestmain** [comment]
t020605 Asia China

**Comment by liuyongmingeth** [comment]
t08264 Asia China

**Comment by wangquanzhou1987** [comment]
t07819 t08937 Asia China

**Comment by planbfilecoin** [comment]
t019133 Europe planB

**Comment by maobisheng** [comment]
t01231 Asia China
t016398 Asia China

**Comment by dineshshenoy** [comment]
https://github.com/filecoin-project/slingshot/pull/88

**Comment by yablu** [comment]
`lotus version 0.8.0+git.2c1d96bc` t08403 Europe (TippyFlits)

**Comment by funktafide** [comment]
Daemon:  0.8.0+git.2c1d96bc+api0.16.0
Local: lotus version 0.8.0+git.2c1d96bc
Daemon:  0.8.0+git.2c1d96bc+api0.15.0
Local: lotus-miner version 0.8.0+git.2c1d96bc

t014768

Asia (Singapore)

Slack - Funk

**Comment by 2019jack** [comment]
t020940 Asia China

**Comment by vht210** [comment]
t01277  Europe (Tung)

**Comment by j1v** [comment]
lotus version `0.8.0+git.2c1d96bc`
miner id : `t020373`
location : `Bulgaria`
slack handle : `j1v`

**Comment by leviok** [comment]
lotus version `0.8.0+git.2c1d96bc`
miner id: t01782
location: asia
slack handle: leviok

**Comment by damco70** [comment]
lotus version 0.8.0+git.2c1d96bc

**Comment by liuyongmingeth** [comment]
t08264 Asia China

**Comment by ericnjin** [comment]
lns@lns-TRX40-AORUS-XTREME:~/scripts$ lotus version
Daemon:  0.8.0+git.2c1d96bc.dirty+api0.16.0
Local: lotus version 0.8.0+git.2c1d96bc.dirt

minerID: t020904 
location: Asia South Korea-Seoul 
slack handle : EricKim

**Comment by alison-man** [comment]
lotus version 0.8.0+git.2c1d96bc
miner ID : t02619
location : Asia China
slack handle : litianc

**Comment by Meatball13** [comment]
lotus version 0.8.0+git.2c1d96bc
minerID: t014409
location: North America
slack handle: Meatball

**Comment by bagzyBoo** [comment]
lotus version 0.8.0+git.2c1d96bc
miner id:  t019029
location: Europe
slack handle: Ninoslav Barzilovic

**Comment by clarenous** [comment]
lotus version 0.8.0+git.2c1d96bc
minerID: t015662
location: Asia China
slack handle: Clarence

**Comment by Reiers** [comment]
**minerID:** t022352
**location:** Asker, Norway
**slack handle:** Reiers

```
Daemon:  0.8.0+git.2c1d96bc+api0.16.0
Local: lotus version 0.8.0+git.2c1d96bc
```

_- TechHedge_

**Comment by whyshy** [comment]
lotus version 0.8.0+git.2c1d96bc
MinerID: t03339
Location: Asia (CN)
Slack Handle: hehe

**Comment by Eliovp** [comment]
- 0.8.0+git.2c1d96bc
- t01234 
- Europe 
- Pvoile

**Comment by kikakkz** [comment]
t022111 Asia China

**Comment by Jason-Cui** [comment]
0.8.0+git.2c1d96bc.dirty
t021337
Asia China
Jason C

**Comment by Jason-Cui** [comment]
0.8.0+git.2c1d96bc.dirty
t01152
Asia China
Jason C

**Comment by rjan90** [comment]
**Lotus Version:** lotus version 0.8.0+git.2c1d96bc
**MinerID:** t08949
**Location:** Oslo, Norway - Europe
**Slack Handle:** Phi-rjan

**Comment by xueyang** [comment]
Lotus Version: lotus version 0.8.0+git.2c1d96bc
MinerID: t010495
Location: China - Asia
Slack Handle: lssr

**Comment by JCui-linpole** [comment]
Miner ID: t08091, Lotus version: 0.8.0+git.2c1d96bc.dirty+api0.16.0, Location: China

**Comment by mingchuantaiwang** [comment]
lotus version 0.8.0+git.2c1d96bc
MinerID：t020358
Location: China - Asia
Slack Handle: delphe

**Comment by transekvs** [comment]
lotus version: lotus version 0.8.0+git.2c1d96bc
MinerID: t015747
Location: Japan - Asia
Slack Handle: meki

**Comment by mingchuantaiwang** [comment]
lotus version 0.8.0+git.2c1d96bc
MinerID：t020358
Location: China - Asia
Slack Handle: delphe

**Comment by wulengbing** [comment]
lotus version 0.8.0+git.2c1d96bc
MinerID：t03328
Location: China - Asia
Slack Handle: kevinyang

**Comment by kwuaint** [comment]
version 0.8.0+git.904c7f6f

**Comment by yydfjt** [comment]
t02405, China, Asia

**Comment by hoomx** [comment]
t08073  China, Asia

**Comment by kikakkz** [comment]
t7824 China, Asia

**Comment by gh3990** [comment]
lotus :  version 0.8.0+git.2c1d96bc.dirty
miner : t010446
Location : Europe, NL
Slack : Angelo

**Comment by mxz9102** [comment]
lotus version 0.8.0+git.2c1d96bc
miner : t09848
Location : California, North America
Slack : BigBear

**Comment by csj202008** [comment]
lotus version 0.8.0+git.2c1d96bc.dirty
miner: t09589
Location: China, Asia
Slack: hxf1983

**Comment by ocean-token** [comment]
t07982 China Asia (tim)

**Comment by rsww-filecoin** [comment]
lotus version 0.8.0+git.2c1d96bc
miner : t02419
location : China - Asia
slack name : rsww

**Comment by quantumgw** [comment]
t018501 Asia China
lotus version 0.8.0+6block+git.a696dd70.1601114956

**Comment by ec2** [comment]
Lotus Version: lotus version 0.8.0+git.2c1d96bc
Miner ID: t01247
Location: North America
Slack Handle: Eric Tu [ChainSafe]

**Comment by shannon-6block** [comment]
lotus version 0.8.0+6block+git.a696dd70.dirty.1601111661
miner: t01241, t02623, t02514, t02501, t02622, t07850, t03274, t03275, t03273, t05315, t08383, t010241, t010253, t05316, t05317, t09696, t09693
Location: China, Asia
Slack: 6block.com


The lotus version is customized by us and I don't know if it has any influence.

**Comment by xupeng9** [comment]
lotus version 0.8.0+6block+git.a696dd70.dirty.1601111661
miner: t02645,t02633,t02415,t07990,t08025,t03491,t018782,t018784,t018781,t018785,t018780,t018783
Location: China, Asia
Slack: Eric G
The lotus version is customized by us and I don't know if it has any influence.

**Comment by backlight** [comment]
lotus version 0.8.0+6block+git.a696dd70.1601114956
miner:t016594
location:Europe, FL
slack:Hive blockchain

**Comment by Shekelme** [comment]
Lotus version:
> Daemon:  0.8.0+git.2c1d96bc.dirty+api0.16.0
> Local: lotus version 0.8.0+git.2c1d96bc.dirty

Location: Russian Federation
Slack: Rabinovitch
Miner: t08240

**Comment by wangquanzhou1987** [comment]
Daemon:  0.8.0+git.2c1d96bc+api0.16.0
lotus version 0.8.0+git.2c1d96bc
miner:t08937  t07819
Location: China, Asia
Slack: YCWL

**Comment by 3p2eo2p3** [comment]
root@Young:~# lotus --version
lotus version 0.8.0+git.2c1d96bc.dirty
(customized)

t015898
Europe

**Comment by benjaminh83** [comment]
lotus version 0.8.0+git.2c1d96bc
miner ID : t02576
location : Copenhagen, Denmark, Europe
slack handle : BenjaminH

**Comment by DxtYan** [comment]
lotus version 0.8.0+git.2c1d96bc
miner ID : t019661
location : Pyatigorsk, Russia
slack handle : dxtyan

**Comment by skm-cike** [comment]
Daemon:  0.8.0+git.2c1d96bc.dirty+api0.16.0
Local: lotus version 0.8.0+git.2c1d96bc.dirty
miner: t02421 t016563
Location: China, Asia
Slack:  lhk522

**Comment by troo** [comment]
lotus version 0.8.0+git.2c1d96bc
Location: Russia
Slack: troo
Miner: t019174

**Comment by NealLiu-Test2** [comment]
lotus version 0.8.0+git.22da31c9.dirty
Location: Asia China
Slack: Neal
Miner: t02490

The lotus version is customized by us and I don't know if it has any influence

**Comment by UltraVis** [comment]
lotus version 0.8.0+git.2c1d96bc
Miner ID: t014324
Location: North America
Slack handle:  UltraVis

**Comment by Jello** [comment]
Daemon:  0.8.0+git.2c1d96bc+api0.16.0
Local: lotus version 0.8.0+git.2c1d96bc
Miner ID: t016056 (weakman)
Location: North America
Slack Handle: Paul

**Comment by Tracerbullet14** [comment]
lotus version 0.8.0+git.2c1d96bc
Miner ID: t019279
Location: North America
Slack Handle: TracerBullet

**Comment by kernelogic** [comment]
Lotus version 0.8.0+git.2c1d96bc
minerID: t010617
Location: North America
Slack: feiya200

**Comment by bobjiang** [comment]
lotus version
lotus-miner version 0.8.0+git.2c1d96bc

miner id
t015685

location
Shanghai/China

slack
Bob Jiang

**Comment by PolygonalMonkey** [comment]
lotus version 0.8.0+git.2c1d96bc
miner ID : t022395
location : North America
slack handle : Clos

**Comment by xueyang** [comment]
Lotus Version: lotus version 0.8.0+git.2c1d96bc
MinerID: t010495
Location: China
Slack Handle: lssr

**Comment by igdx** [comment]
lotus version 0.8.0+git.2c1d96bc
miner:t010558 t019196 
Location: China, Asia
Slack: Ron

**Comment by coinmini** [comment]
lotus version 0.8.0+git.2c1d96bc
miner: t08157
Location: Europe ,China
Slack: JerseyJerry, renkeju

**Comment by AthenaPool** [comment]
Hi Filecoin Team, please check the following miners and add them to the recommended miners:
t02614 t09652 Asia
t03362 Europe
t010424 Oceania
Thanks

**Comment by crystalangie** [comment]
lotus version:0.8.0+git.b22bb528.dirty
miner ID: t019638
location: Singapore, Asia
handle: Crystal Han

**Comment by hsienfu** [comment]
Miner ID: t020436
Location: Asia China
Slack: iseefoo

**Comment by s0nik42** [comment]
lotus version 0.8.0+git.2c1d96bc.dirty
minerid : t010479
Location : France / Europe
Slack : s0nik42

**Comment by flyworker** [comment]
Miner ID:        t02401
                      t01276
                      t02387
lotus version 0.8.0+git.2c1d96bc
Location : Canada / North America
Slack : Charles Cao - NBFS

**Comment by callmestu** [comment]
Miner: t016482
lotus-miner version 0.8.0+git.2c1d96bc
Location: USA
Slack: callmestu

**Comment by maruoshui** [comment]
lotus version 0.8.0+git.2c1d96bc
minerID: t010512
location: Asia China
slack handle: Maruoshui

**Comment by namoo1** [comment]
lotus version 0.8.0+git.2c1d96bc
miner id: t03488, t022737
location: asia South korea
slack handle: Meest Nam

**Comment by dineshshenoy** [comment]
Updated all miners above https://github.com/filecoin-project/slingshot/pull/99

**Comment by kaoxiang07** [comment]
lotus version 0.8.0+git.2c1d96bc.dirty
minerID: t03134
location: Asia China
slack handle: William

**Comment by cryptowhizzard** [comment]
Local: lotus version 0.8.0+git.2c1d96bc
minerID: t01240
Location: Europe
Slack handle: Wijnand Schouten

**Comment by hengic** [comment]
lotus version 0.8.0+git.2c1d96bc
minerID: t010507
location: Asia China
slack handle: H.J

**Comment by ffteng46** [comment]
lotus version 0.8.0+git.2c1d96bca.dirty
miner:t04443
Location: China, Asia
Slack: jjxiaoke

**Comment by sypro2020** [comment]
lotus version 0.8.0+git.2c1d96bc.dirty
miner:t03624
Location: Europe Germany
Slack: Sonne

**Comment by superlone** [comment]
lotus version 0.8.0+git.2c1d96bc.dirty
minerID: t08474
location: Asia China
slack handle: lone

**Comment by sypro2020** [comment]
你好，

你给我发邮件干啥？

Am 27. September 2020 um 14:22:55 +02:00, hat superlone <notifications@github.com> geschrieben:

**Comment by superlone** [comment]
lotus version 0.8.0+git.2c1d96bc.dirty
 minerID: t08474
 location: Asia China
 slack handle: lone

**Comment by Jason-Cui** [comment]
0.8.0+git.2c1d96bc.dirty
t022832
Asia China
Jason C

**Comment by iverytang** [comment]
lotus version 0.8.0+git.2c1d96bc
miner ID: t09569
location: China, Asia
slack handle: jjxx

**Comment by jjxx2021** [comment]
lotus version 0.8.0+git.2c1d96bc
miner ID : t09569
location : Asia China
slack handle : jjxx

**Comment by igowreck** [comment]
Daemon:  0.8.0+git.2c1d96bc+api0.16.0
Local: lotus version 0.8.0+git.2c1d96bc
miner ID : t03224, t015941, t02423
location : Europe, Ukraine, Kyiv
slack handle : igowreck

**Comment by monkey262507** [comment]
t010035  t021255  Asia China

**Comment by dineshshenoy** [comment]
Moved from: https://github.com/filecoin-project/slingshot/issues/117

Please add t020352 Europe Moscow

**Comment by dineshshenoy** [comment]
Updated above miners at: https://github.com/filecoin-project/slingshot/pull/120

**Comment by aimkiray** [comment]
lotus version 0.8.0+git.05f947393
minerID: t022038
location: Asia China

**Comment by flyworker** [comment]
Miner ID: **t02401**
lotus version 0.8.0+git.2c1d96bc
Location : Canada / North America
Slack : Charles Cao - NBFS

**Comment by crystalangie** [comment]
lotus version:0.8.0+git.b22bb528.dirty
miner ID: t03363
location: Singapore, Asia
handle: Crystal Han

**Comment by cerblue** [comment]
Lotus version: 0.8.0+git.2c1d96bc.dirty+api0.16.0
Miner ID: t010088
Location: USA
Slack: Kltaway

**Comment by dayou5168** [comment]
lotus version 0.8.0+git.2c1d96bc
miner ID : t02775 t02770 t02767
location : china
slack handle : barry
slack handle : jerry
slack handle : da-you

**Comment by NSC-FIL** [comment]
Lotus version 0.8.0+git.2c1d96bc
Miner ID: t022142
Location: New York / North America
Slack Handle: Nelson

**Comment by dineshshenoy** [comment]
t022142 Nelson North America

**Comment by yangjian102621** [comment]
MinerID: t09620,t09675
Location: Asia (CN)
Slack Handle: RockYang

**Comment by h1tthat** [comment]
lotus version 0.8.0+git.2c1d96bc
miner ID: t022405
Location: Europe Moscow
Slack Handle: Oleg Kaizen

**Comment by livspect** [comment]
Lotus Version: 0.8.0+git.b84cc46c
Miner ID: t020771
Location: Asia Japan
Slack: livspect

**Comment by rjan90** [comment]
Lotus Version: lotus version 0.8.0+git.2c1d96bc
MinerID: t023467
Location: Oslo, Norway - Europe
Slack Handle: Phi-rjan

**Comment by ocean-token** [comment]
t023229 Asia China

**Comment by dineshshenoy** [comment]
All miners above have been merged.  https://github.com/filecoin-project/slingshot/pull/173

**Comment by wqz8791** [comment]
lotus version :
Daemon:  0.8.0+git.bc85e3ce+api0.16.0
Local: lotus version 0.8.0+git.bc85e3ce
MinerID: t023202
Location: Asia (wuxi China)
Slack Handle: YCWL

**Comment by std** [comment]
lotus version 0.8.0+git.2c1d96bc
miner ID: t08285
Location: Europe Latvia
Slack Handle: stander

**Comment by sdm101** [comment]
lotus version 0.8.0+git.6025bcea
miner ID: t023586
Location North America
Slack Handle: Brian Y

**Comment by dineshshenoy** [comment]
Miners above added:  https://github.com/filecoin-project/slingshot/pull/189

**Comment by mattac21** [comment]
lotus version: v0.8.1
miner ID: t02540
Location: North America
Slack Handle: there

**Comment by namoo-cloud** [comment]
> lotus version 0.8.0+git.2c1d96bc
> miner id: t03488, t022737
> location: asia South korea
> slack handle: Meest Nam

t03488 now repairing. I will back soon. Thx.

**Comment by Storage-Hive** [comment]
lotus version 0.8.1+git.60d442e3
Miner: t010438
Location: North America
Slack: StorageHive

**Comment by coinmini** [comment]
lotus version 0.8.0+git.2c1d96bc
miner ID: t08157
Location: Europe,China
Slack Handle: JerseyJerry, renkeju

**Comment by boramida** [comment]
> lotus version 0.8.0+git.2c1d96bc
> miner id: t03488, t022737
> location: asia South korea
> slack handle: Meest Nam

Now repiar Miner t03488 and t022737

**Comment by hxg8202** [comment]
lotus version 0.8.0+git.2c1d96bc
miner id: t010254
location: asia japan
slack handle: anglebaby

**Comment by 8hfq** [comment]
lotus version 0.8.0+git.2c1d96bc
miner id: t015877   t023678
location: Asia China
slack handle: 8HFQ

**Comment by ncgege** [comment]
lotus version Daemon:  0.8.1+git.60d442e3.dirty+api0.16.0
miner ID: t022566
Location: China
Slack Handle: ncgege

**Comment by sdm101** [comment]
lotus version 0.8.0+git.2c1d96bc
miner ID: t023826
Location: North America
Slack Handle: Brian Y (testing out another mining machine w/ new miner)

**Comment by sdm101** [comment]
lotus version 0.8.1+git.4631cee5
miner id: t023971
Location: North America
Slack Handle: Brian Y (initialized new miner to test different configuration).

**Comment by yuyuyun01** [comment]
lotus version 0.8.1+git.60d442e3.dirty
miner id: t024070
Location: Japan
Slack Handle: ychikn

**Comment by axzmin** [comment]
Lotus Version: 0.8.1+git.1ebad94d
Miner ID: t010399
Location: Asia China
Slack: axzmin

**Comment by Yarkin** [comment]
Lotus Version: 0.8.0
Miner ID: t02301
Location: North America
Slack: justin

**Comment by Yarkin** [comment]
Lotus Version: 0.8.0
Miner ID: t03223
Location: North America
Slack: justin

**Comment by planbfilecoin** [comment]
lotus version 0.8.1
miner ID t024150
location Europe
slack planB

**Comment by dineshshenoy** [comment]
Above updated with https://github.com/filecoin-project/slingshot/pull/211

**Comment by kenshyx** [comment]
lotus version 0.8.1+git.2bf42d531
Miner: f022163
Location: Europe
Slack: @Marius

**Comment by DenysSuccess** [comment]
lotus version 0.8.1+git.60d442e3
Miner: t023490
Location: Europe
Slack: Dennis

**Comment by LutherSun** [comment]
lotus version 0.8.0+git.2c1d96bca
Miner: t010010
Location: Asia China
Slack: LutherSun(U01480QEWQ5)

**Comment by ocean-token** [comment]
t025025 Asia China

**Comment by dineshshenoy** [comment]
Updated miners with f prefix.  https://github.com/filecoin-project/slingshot/pull/240

**Comment by wqz8791** [comment]
lotus version:
Daemon:  0.9.0+git.8f35a5c0+api0.16.0
Local: lotus version 0.9.0+git.8f35a5c0
Miner: f029556
Location: Asia China  Wuxi

**Comment by coinmini** [comment]
lotus version: 0.9.0+git.8f35a5c0
Miner: f08157
Location:  Asia, Europe

**Comment by liuyongmingeth** [comment]
lotus version: 0.9.0+git.8f35a5c0
Miner: f08264
Location: Asia, china

**Comment by namoo-cloud** [comment]
Daemon:  0.9.0+git.8f35a5c03+api0.15.0
Local: lotus-miner version 0.9.0+git.8f35a5c03
Miner: f03488
Location: South korea

**Comment by wqz8791** [comment]
lotus version:
Daemon:  0.9.1+git.40b2e2d0+api0.16.0
Local: lotus version 0.9.1+git.40b2e2d0
Miner: f07819
Location: Asia China Wuxi

**Comment by PINBYTES** [comment]
lotus version: 09.9.1+git.651522cb
Miner : t025007
Location : Seoul, Korea

**Comment by PINBYTES** [comment]
lotus version: 0.9.1+git.651522cb
Miner : t025007
Location : Seoul, Korea

**Comment by PINBYTES** [comment]
lotus version: 0.9.1+git.651522cb 
Miner: t025007
Location: Seoul, Korea

**Comment by coinmini** [comment]
lotus version: 0.10.0+git.a6b21807
Miner: f08157
Location: Asia

**Comment by livspect** [comment]
lotus version: 0.10.0+git.443131b2
Miner: f032835
Location: Japan

**Comment by dineshshenoy** [comment]
Updated above with PR:  #267

**Comment by sdm101** [comment]
lotus version: 0.10.0+git.65883cbb
Miner: f023971
Location: North America

**Comment by wqz8791** [comment]
lotus version: 
Daemon:  0.10.0+git.9c6ee802c+api0.16.0
Local: lotus version 0.10.0+git.9c6ee802c
Miner: f033113
Location: WuXI , China , Asia

**Comment by dineshshenoy** [comment]
Updated above with PR: https://github.com/filecoin-project/slingshot/pull/290

**Comment by wqz8791** [comment]
lotus version:
Daemon:  0.10.2+git.0775c6c9d+api0.17.0
Local: lotus version 0.10.2+git.0775c6c9d
MinerID：f07819  f033113  f033091  f034216  f039712 
Location:  WuXi  China - Asia
Slack Handle:YCWL

**Comment by neondragon** [comment]
lotus version: 0.10.1+git.41bfeb56e
Miner: f019551
Location: Europe (United Kingdom)
Slack: Neonix AF

**Comment by dineshshenoy** [comment]
Updated above with PR #329

**Comment by aimkiray** [comment]
Lotus Version: 0.10.0
Miner ID: f034047
Location: Asia China
Slack: fox

**Comment by dineshshenoy** [comment]
Updated above with PR #342

**Comment by mattac21** [comment]
Lotus Version: v1.1.0
Miner ID: f02540
Location: North America
Slack: there

**Comment by powerboy11** [comment]
Lotus Version: v1.1.0
Miner ID: f049882
Location: Europe
Slack: Ducktales

**Comment by rovdi** [comment]
Miner ID: f040173
Location: Ukraine
Slack: Wolanski

**Comment by dineshshenoy** [comment]
Updated above with PR #346

**Comment by dineshshenoy** [comment]
No longer being updated since Slingshot Phase 1 is complete.   There are other public resources such as [Codefi](https://www.storage.codefi.network/) and others which can help find reputable and affordable miners.
